### PR TITLE
Add pipeline for migrations

### LINKED ISSUE #163: Setup migration pipeline
- [x] Add command functionality in review process for updating database.
- [x] Add workflow to inform users that they have to run the command for PR's where there were migration changes
- [x] ~~Fix bug: Mergeable is true before checks are passing~~
Used PR review status instead

### PR DESCRIPTION
**Pull request by GodVenn**
Closes #163

### CODE REVIEW

**Comment by GodVenn** [comment]
Testing testing

**Comment by VegardOztan** [comment]
Problem: When running updateDatabase.yml by writing /UpdateDatabase, it runs on main branch, which does not have the migration pending.

Solution: Need to specify to updateDatabase.yml that it needs to run on the branch that triggered the workflow

**Comment by VegardOztan** [comment]
Another problem: We can't write / Update Database (no space) in a comment without the job being run. Should only run if comment only contains the keyword?

**Comment by GodVenn** [comment]
Testing not literal /UpdateDatabase

**Review by VegardOztan — APPROVED** [review]

**Review by VegardOztan — DISMISSED** [review]

**Comment by GodVenn** [comment]
Hello

**Review by GodVenn — COMMENTED** [review]
Test review

**Review by VegardOztan — DISMISSED** [review]

**Review by VegardOztan — APPROVED** [review]

**Review by VegardOztan — APPROVED** [review]

**Pull request closed without merging**
